# TODO: Enable once https://github.com/prettier/prettier/issues/3845 has been added
printWidth: 140
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
trailingComma: none
bracketSpacing: false
arrowParens: always
parser: typescript
requirePragma: false
insertPragma: false
endOfLine: lf
