version: "3"

networks:
  breeze:
    driver: bridge

services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: breeze
      MYSQL_PASSWORD: password
    networks:
      - breeze
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
